reddit_capybara_practice/config/routes.rb
RedditOnRails::Application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :comments, only: [:create, :show] do
    member do
      post "downvote"
      post "upvote"
    end
  end
  resources :subs, except: [:destroy]
  resources :posts, except: [:destroy, :index] do
    resources :comments, only: [:new]
    member do
      post "downvote"
      post "upvote"
    end
  end

  root to: redirect("/subs")
end

reddit_capybara_practice/app/models/post.rb
class Post < ActiveRecord::Base
  include Votable

  validates :author, :title, presence: true

  has_many :post_subs, inverse_of: :post, dependent: :destroy
  has_many :subs, through: :post_subs, source: :sub
  has_many :comments, inverse_of: :post

  # Using polymorphic assocations without a concern
  has_many :user_votes, as: :votable, class_name: "UserVote"

  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :user_id,
    inverse_of: :posts
  )

  def comments_by_parent
    comments_by_parent = Hash.new { |hash, key| hash[key] = [] }

    self.comments.includes(:author).each do |comment|
      comments_by_parent[comment.parent_comment_id] << comment
    end

    comments_by_parent
  end

  # Without a concern, we have to write a #votes method for each votable class
  # def votes
  #   self.user_votes.sum(:value)
  # end
end

reddit_capybara_practice/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_signed_in!, except: [:show]
  before_action :require_user_owns_post!, only: [:edit, :update]

  def new
    @post = Post.new
    render :new
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def downvote; vote(-1); end
  def upvote; vote(1); end

  private
  def post_params
    params.require(:post).permit(
      :url, :title, :content, :user_id, sub_ids: []
    )
  end

  def require_user_owns_post!
    return if Post.find(params[:id]).author == current_user
    render json: "Forbidden", status: :forbidden
  end

  def vote(direction)
    @post = Post.find(params[:id])
    @user_vote = UserVote.find_by(
      votable_id: @post.id, votable_type: "Post", user_id: current_user.id
    )

    if @user_vote
      @user_vote.update(value: direction)
    else
      @post.user_votes.create!(
        user_id: current_user.id, value: direction
      )
    end

    redirect_to post_url(@post)
  end
end

reddit_capybara_practice/app/views/posts/_form.html.erb
<% action_url = post.persisted? ? post_url(post) : posts_url %>
<% http_method = post.persisted? ? "PATCH" : "POST" %>

<form action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= http_method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label>
    Title:
    <input name="post[title]" value="<%= post.title %>">
  </label>
  <br>

  <label>
    URL:
    <input name="post[url]" value="<%= post.url %>">
  </label>
  <br>

  <label>
    Content:
    <textarea name="post[content]"><%= post.content %></textarea>
  </label>
  <br>

  <input type="hidden" name="post[sub_ids][]" value="">
  <% Sub.all.each do |sub| %>
    <label>
      <input
        type="checkbox"
        name="post[sub_ids][]"
        value="<%= sub.id %>"
        <%= "checked" if post.sub_ids.include?(sub.id) %>>
      <%= sub.name %>
    </label>
    <br>
  <% end %>

  <input type="Submit" value="Submit">
</form>

reddit_capybara_practice/app/views/posts/edit.html.erb
<div class="border">
  <h1>Edit Post!</h1>

  <%= render "form", post: @post %>
</div>

reddit_capybara_practice/app/views/posts/new.html.erb
<div class="border">
  <h1>New Post!</h1>

  <%= render "form", post: @post %>
</div>

reddit_capybara_practice/app/views/posts/show.html.erb
<div class="border">
  <h1>
    (<%= @post.votes %>)
    <%= link_to @post.title, post_url(@post) %> by
    <%= @post.author.name %>
  </h1>

  <div class="small-border"
    <b>Content:</b>

    <pre><%= @post.content %></pre>
    <br><br>
  </div>

  <%= button_to "Upvote", upvote_post_url(@post) %>
  <%= button_to "Downvote", downvote_post_url(@post) %>

  <br>
  <b>Subs</b>
  <ul>
    <% @post.subs.each do |sub| %>
      <li><%= link_to sub.name, sub_url(sub) %></li>
    <% end %>
  </ul>

  <h2>Comments</h2>

  <%= link_to "Comment on this post!", new_post_comment_url(@post.id) %>
  <br><br>

  <ul>
    <% comments_by_parent = @post.comments_by_parent %>
    <% comments_by_parent[nil].each do |top_level_comment| %>
      <li>
        <%= render("comments/comment",
                   comment: top_level_comment,
                   comments_by_parent: comments_by_parent) %>
      </li>
    <% end %>
  </ul>

  <%= link_to "Edit", edit_post_url(@post) if @post.author == current_user %>
</div>